language: node_js

node_js:
  - 10.0
  - node

install:
  - npm install

script:
  - echo "Running tests against $(node -v) ..."

# Send coverage data to Coveralls
# after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
